name: Windows-x64-vs2017

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  pull_request:
    branches: [master]
    paths-ignore: ['**.md']

jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure CMake
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug
  
    - name: Build and test
      run: |
        cd build
        cmake --build . --config Debug -j 2
    